#!/usr/bin/env python3
"""mesh_to_monado.py — convert Meta's baked distortion mesh into a Monado-consumable form.

Monado's `u_distortion_mesh` is driven by a callback of the shape

    bool func(struct xrt_device *xdev, uint32_t view, float u, float v,
              struct xrt_uv_triplet *result)

taking a normalised (u, v) in [0,1] over the *render target* and returning three sample UVs, one per
colour channel, also normalised. Meta's mesh (`notes/42`) is a 33x33 grid per eye with three
channels, so this is a resampling and renormalisation job, not a model fit.

What is emitted: a C header with the grid baked in, plus a bilinear sampler with exactly Monado's
callback signature, so a driver can call it directly.

HONEST LIMIT — read before trusting the output geometrically. Meta's vertex coordinates are not
normalised UVs; they span about -3.8..3.6, and the extremes correspond to ~75 degrees of half-angle,
which is *consistent with* a tangent-space parameterisation given the header's 42-53 degree FOV
values (`notes/42`). That interpretation is not proven. This converter therefore normalises by the
mesh's own min/max extent per eye, which is correct if the grid is a uniform sampling of the render
target (which its 100 % monotonicity in both axes supports) and wrong if the sampling is non-uniform
in a way not yet characterised.

Concretely: the *topology* and the *chromatic offsets* are certainly right; the absolute mapping to
field angles is pending confirmation against a rendered comparison with the stock compositor. Until
that comparison is done, treat the output as structurally correct and metrically provisional.

Usage: mesh_to_monado.py <distortion-mesh.bin> [-o out.h] [--json out.json]
"""
import argparse
import json
import struct
import sys

import numpy as np

HDR = 96
N = 33
NV = 2178
ROWS = 66


def decode(path):
    d = open(path, 'rb').read()
    magic, = struct.unpack('<I', d[:4])
    if magic != 0x56347807:
        raise SystemExit(f'bad magic {magic:#x}')
    panel_w, panel_h, eye_w, eye_h = struct.unpack('<4I', d[0x30:0x40])
    fov = struct.unpack('<8f', d[0x40:0x60])
    f = np.frombuffer(d[HDR:], dtype='<f4')
    grid = f.reshape(ROWS, N, 3, 2)
    return (grid[0::2], grid[1::2]), dict(panel=(panel_w, panel_h), eye=(eye_w, eye_h), fov=fov)


def normalise(eye):
    """Map the mesh's own coordinate range onto [0,1] per eye, green channel setting the extent.

    Green is used as the reference so the R and B meshes keep their *relative* chromatic offsets
    rather than each being stretched to fill [0,1], which would destroy the aberration correction.
    """
    g = eye[:, :, 1, :]
    lo = np.array([g[..., 0].min(), g[..., 1].min()])
    hi = np.array([g[..., 0].max(), g[..., 1].max()])
    return (eye - lo) / (hi - lo), lo, hi


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('mesh')
    ap.add_argument('-o', '--out', default='quest1_distortion_mesh.h')
    ap.add_argument('--json', dest='js')
    a = ap.parse_args()

    eyes, meta = decode(a.mesh)
    norm, extents = [], []
    for i, e in enumerate(eyes):
        ne, lo, hi = normalise(e)
        norm.append(ne)
        extents.append((lo.tolist(), hi.tolist()))
        g = ne[:, :, 1, :]
        xr = np.mean([np.all(np.diff(g[r, :, 0]) > 0) for r in range(N)])
        yc = np.mean([np.all(np.diff(g[:, c, 1]) > 0) for c in range(N)])
        oob = float(np.mean((ne < -0.05) | (ne > 1.05)))
        dr = np.abs(ne[:, :, 0, :] - ne[:, :, 1, :]).mean()
        db = np.abs(ne[:, :, 2, :] - ne[:, :, 1, :]).mean()
        print(f"eye{i}: monotonic x-rows {xr*100:.0f}% y-cols {yc*100:.0f}%  "
              f"out-of-range {oob*100:.2f}%  chroma |R-G| {dr:.5f} |B-G| {db:.5f}")

    with open(a.out, 'w') as f:
        f.write("// Generated by tools/display/mesh_to_monado.py from Meta's\n"
                "// /system/etc/calibration/distortion-mesh.bin (Quest 1 'monterey').\n"
                "// Layout and provenance: notes/42, notes/44. Metrically provisional: see the\n"
                "// converter docstring before relying on absolute field angles.\n"
                "#pragma once\n#include <stdint.h>\n#include <stdbool.h>\n\n")
        f.write(f"#define QUEST1_MESH_N {N}\n")
        f.write(f"#define QUEST1_PANEL_W {meta['panel'][0]}\n#define QUEST1_PANEL_H {meta['panel'][1]}\n")
        f.write(f"#define QUEST1_EYE_W {meta['eye'][0]}\n#define QUEST1_EYE_H {meta['eye'][1]}\n\n")
        f.write("// [eye][row][col][channel R,G,B][u,v], normalised to [0,1]\n")
        f.write(f"static const float quest1_mesh[2][{N}][{N}][3][2] = {{\n")
        for e in norm:
            f.write("{\n")
            for r in range(N):
                f.write("{" + ",".join("{" + ",".join(f"{{{e[r,c,ch,0]:.6f}f,{e[r,c,ch,1]:.6f}f}}"
                                                      for ch in range(3)) + "}" for c in range(N)) + "},\n")
            f.write("},\n")
        f.write("};\n\n")
        f.write("""// Bilinear sample of the mesh. Signature matches Monado's u_distortion_mesh callback
// body: given normalised (u,v) over the render target, return one UV per colour channel.
static inline bool
quest1_mesh_sample(uint32_t view, float u, float v, float out_r[2], float out_g[2], float out_b[2])
{
\tif (view > 1u || u < 0.0f || u > 1.0f || v < 0.0f || v > 1.0f) return false;
\tconst float fx = u * (QUEST1_MESH_N - 1), fy = v * (QUEST1_MESH_N - 1);
\tint x0 = (int)fx, y0 = (int)fy;
\tif (x0 >= QUEST1_MESH_N - 1) x0 = QUEST1_MESH_N - 2;
\tif (y0 >= QUEST1_MESH_N - 1) y0 = QUEST1_MESH_N - 2;
\tconst float tx = fx - (float)x0, ty = fy - (float)y0;
\tfloat *outs[3] = { out_r, out_g, out_b };
\tfor (int ch = 0; ch < 3; ch++) {
\t\tfor (int k = 0; k < 2; k++) {
\t\t\tconst float a = quest1_mesh[view][y0][x0][ch][k];
\t\t\tconst float b = quest1_mesh[view][y0][x0 + 1][ch][k];
\t\t\tconst float c = quest1_mesh[view][y0 + 1][x0][ch][k];
\t\t\tconst float d = quest1_mesh[view][y0 + 1][x0 + 1][ch][k];
\t\t\touts[ch][k] = (a * (1 - tx) + b * tx) * (1 - ty) + (c * (1 - tx) + d * tx) * ty;
\t\t}
\t}
\treturn true;
}
""")
    print(f"wrote {a.out}")
    if a.js:
        json.dump(dict(mesh=[e.tolist() for e in norm], extents=extents,
                       panel=meta['panel'], eye=meta['eye'], fov=list(meta['fov'])),
                  open(a.js, 'w'))
        print(f"wrote {a.js}")


if __name__ == '__main__':
    main()
