#!/bin/sh
# Regenerate msm_ioctl_table.h from the published kernel uapi headers.
#
# The point is that no ioctl number is ever transcribed by hand: the table stores the *macro*, so
# the compiler computes each code from the same headers the kernel uses. If a header changes, the
# table follows. Names are harvested from the headers too, so the list cannot drift out of sync.
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
K=$(cd "${1:-$HERE/../../work/oculus-kernel}" && pwd)
MEDIA="$K/include/uapi/media"
OUT="$HERE/msm_ioctl_table.h"
HDRS="msmb_camera.h msmb_generic_buf_mgr.h msmb_isp.h msmb_ispif.h msm_cam_sensor.h"

[ -d "$MEDIA" ] || { echo "no such dir: $MEDIA" >&2; exit 1; }

NAMES=$(cd "$MEDIA" && for f in $HDRS; do
          grep -oE '^#define ((VIDIOC_MSM|MSM_CAM_V4L2_IOCTL)[A-Z0-9_]*)' "$f" | awk '{print $2}'
        done | sort -u)

{
  echo '// GENERATED by gen_ioctl_table.sh -- do not edit'
  echo 'static const struct { unsigned long code; const char *name; } msm_ioctls[] = {'
  for n in $NAMES; do echo "  { (unsigned long)$n, \"$n\" },"; done
  echo '};'
} > "$OUT"
echo "wrote $OUT ($(echo "$NAMES" | wc -w) ioctls)"
